build:
    image: default-jammy
    environment:
        php:
            version: 8.4
            pecl_extensions:
                - redis
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

filter:
    paths: ["src/*"]
