name: Continuous Integration

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"
  SCRIPT: "demo/run.php"

jobs:
  phpunit:
    name: PHPUnit (${{ matrix.os }} - PHP ${{ matrix.php-version }} - ${{ matrix.dependencies }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        php-version: [8.1, 8.2, 8.3, 8.4]
        dependencies: [lowest, highest]
        exclude:
          - php-version: 8.1
            os: ubuntu-latest
          - php-version: 8.1
            dependencies: lowest

    services:
      redis:
        image: redis
        ports: [6379:6379]
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          ini-values: zend.assertions=1
          tools: composer

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-composer-

      - name: Configure dependency resolution
        run: |
          composer config platform --unset

      - name: Update dependencies
        run: composer update ${{ matrix.dependencies == 'lowest' && '--prefer-lowest' || '' }} ${{ env.COMPOSER_FLAGS }}

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          fail_ci_if_error: true

      - name: Prepare and run demo
        if: ${{ env.SCRIPT != '' && matrix.os == 'ubuntu-latest' }}
        run: |
          composer require doctrine/cache:"^1.12" --no-update
          composer update ${{ env.COMPOSER_FLAGS }}
          php ${{ env.SCRIPT }}
